-- queryescape test table
INSERT ALL
INTO todo VALUES(1,'ABCDE1')
INTO todo VALUES(2,'ABCDE2')
INTO todo VALUES(3,'AB%DE1')
INTO todo VALUES(4,'AB%DE2')
INTO todo VALUES(5,'AB_DE1')
INTO todo VALUES(6,'AB_DE2')
INTO todo VALUES(7,'AB％DE1')
INTO todo VALUES(8,'AB％DE2')
INTO todo VALUES(9,'AB＿DE1')
INTO todo VALUES(10,'AB＿DE2')
INTO todo VALUES(11,'AB~DE1')
INTO todo VALUES(12,'AB~DE2')
SELECT * FROM DUAL
