= terasoluna-gfw-web/Validation

org.terasoluna.gfw.common.validatorパッケージのテスト

== Validation テスト

テストケースクラス: `org.terasoluna.gfw.functionaltest.app.validation.ValidationTest`

=== `@ByteMin` アノテーションと属性の確認

[cols="5,5,30,20,20", options="header"]
|===
| 項番
| 観点
| 試験項目
| 試験条件
| 確認内容

| 1.1
| 20X系
| 指定したvalue,chasetの値で、検証が行われること（正常）
a| * String型プロパティに `@ByteMin` を付与する
[source,java]
----
@ByteMin(value = 6,
    charset = "Shift_JIS")
private String property;
----
* 入力値に境界内となる値を入力する
a| * 検証をパスすることを確認する

| 1.2
| 40X系
| 指定したvalue,chasetの値で、検証が行われること（検証エラー）
a| * String型プロパティに `@ByteMin` を付与する
[source,java]
----
@ByteMin(value = 6,
    charset = "Shift_JIS")
private String property;
----
* 入力値に境界外となる値を入力する
a| * 検証をパスせず、プロパティに対するエラーメッセージが表示されることを確認する

| 1.3
| 40X系
| 日本語ロケールを指定した場合に、日本語メッセージが表示されること（検証エラー）
a| * 1.2と同様
* LocaleResolverを利用して日本語ロケールに変更する
a| * 日本語エラーメッセージが表示されること

|===

=== `@ByteMax` アノテーションと属性の確認

[cols="5,5,30,20,20", options="header"]
|===
| 項番
| 観点
| 試験項目
| 試験条件
| 確認内容

| 2.1
| 20X系
| 指定したvalue,charsetの値で、検証が行われること（正常）
a| * String型プロパティに `@ByteMax` を付与する
[source,java]
----
@ByteMax(value = 6,
    charset = "Shift_JIS")
private String property;
----
* 入力値に境界内となる値を入力する
a| * 検証をパスすることを確認する

| 2.2
| 40X系
| 指定したvalue,chasetの値で、検証が行われること（検証エラー）
a| * String型プロパティに `@ByteMax` を付与する
[source,java]
----
@ByteMax(value = 6,
    charset = "Shift_JIS")
private String property;
----
* 入力値に境界外となる値を入力する
a| * 検証をパスせず、プロパティに対するエラーメッセージが表示されることを確認する

| 2.3
| 40X系
| 日本語ロケールを指定した場合に、日本語メッセージが表示されること（検証エラー）
a| * 2.2と同様
* LocaleResolverを利用して日本語ロケールに変更する
a| * 日本語エラーメッセージが表示されること

|===

=== `@ByteSize` アノテーションと属性の確認

[cols="5,5,30,20,20", options="header"]
|===
| 項番
| 観点
| 試験項目
| 試験条件
| 確認内容

| 3.1
| 20X系
| 指定したmin,max,charsetの値で、検証が行われること（正常）
a| * String型プロパティに `@ByteSize` を付与する
[source,java]
----
@ByteSize(min = 6, max = 6,
    charset = "Shift_JIS")
private String property;
----
* 入力値に境界内となる値を入力する
a| * 検証をパスすることを確認する

| 3.2
| 40X系
| 指定したmin,max,chasetの値で、検証が行われること（検証エラー）
a| * String型プロパティに `@ByteSize` を付与する
[source,java]
----
@ByteSize(min = 6, max = 6,
    charset = "Shift_JIS")
private String property;
----
* 入力値に境界外となる値を入力する
a| * 検証をパスせず、プロパティに対するエラーメッセージが表示されることを確認する

| 3.3
| 40X系
| 日本語ロケールを指定した場合に、日本語メッセージが表示されること（検証エラー）
a| * 3.2と同様
* LocaleResolverを利用して日本語ロケールに変更する
a| * 日本語エラーメッセージが表示されること

|===

=== `@Compare` アノテーションと属性の確認

[cols="5,5,30,20,20", options="header"]
|===
| 項番
| 観点
| 試験項目
| 試験条件
| 確認内容

| 4.1
| 20X系
| 指定したleft,right,operator,requireBoth,nodeの値で、検証が行われること（正常）
a| * Integer型プロパティを持つクラスに `@Compare` を付与する
[source,java]
----
@Compare(left = "left",
    right = "right",
    operator = Compare.Operator.EQUAL,
    requireBoth = true,
    node = Compare.Node.PROPERTY)
public class TestClass {
    private Integer left;
    private Integer right;
}
----
* `left` と `right` に同一の値を入力する
a| * 検証をパスすることを確認する

| 4.2
| 40X系
| 指定したleft,right,operator,requireBoth,nodeの値で、検証が行われること（検証エラー）
a| * Integer型プロパティを持つクラスに `@Compare` を付与する
[source,java]
----
@Compare(left = "left",
    right = "right",
    operator = Compare.Operator.EQUAL,
    requireBoth = true,
    node = Compare.Node.PROPERTY)
public class TestClass {
    private Integer left;
    private Integer right;
}
----
* `left` と `right` に異なる値を入力する
a| * 検証をパスせず、プロパティ `right` に対するエラーメッセージが表示されることを確認する

| 4.3
| 20X系
| Compare.Operator.EQUALが有効に働くこと（正常）
a| * Integer型プロパティを持つクラスに `@Compare` を付与する
[source,java]
----
@Compare(left = "left",
    right = "right",
    operator = Compare.Operator.EQUAL)
public class TestClass {
    private Integer left;
    private Integer right;
}
----
* `left` と `right` に同一の値を入力する
a| * 検証をパスすることを確認する

| 4.4
| 40X系
| Compare.Operator.EQUALが有効に働くこと（検証エラー）
a| * Integer型プロパティを持つクラスに `@Compare` を付与する
[source,java]
----
@Compare(left = "left",
    right = "right",
    operator = Compare.Operator.EQUAL)
public class TestClass {
    private Integer left;
    private Integer right;
}
----
* `left` と `right` に異なる値を入力する
a| * 検証をパスせず、プロパティ `left` に対するエラーメッセージが表示されることを確認する

| 4.5
| 20X系
| Compare.Operator.NOT_EQUALが有効に働くこと（正常）
a| * Integer型プロパティを持つクラスに `@Compare` を付与する
[source,java]
----
@Compare(left = "left",
    right = "right",
    operator = Compare.Operator.NOT_EQUAL)
public class TestClass {
    private Integer left;
    private Integer right;
}
----
* `left` と `right` に異なる値を入力する
a| * 検証をパスすることを確認する

| 4.6
| 40X系
| Compare.Operator.NOT_EQUALが有効に働くこと（検証エラー）
a| * Integer型プロパティを持つクラスに `@Compare` を付与する
[source,java]
----
@Compare(left = "left",
    right = "right",
    operator = Compare.Operator.NOT_EQUAL)
public class TestClass {
    private Integer left;
    private Integer right;
}
----
* `left` と `right` に同一の値を入力する
a| * 検証をパスせず、プロパティ `left` に対するエラーメッセージが表示されることを確認する

| 4.7
| 20X系
| Compare.Operator.GREATER_THANが有効に働くこと（正常）
a| * Integer型プロパティを持つクラスに `@Compare` を付与する
[source,java]
----
@Compare(left = "left",
    right = "right",
    operator = Compare.Operator.GREATER_THAN)
public class TestClass {
    private Integer left;
    private Integer right;
}
----
* `left` に `right` より大きな値を入力する
a| * 検証をパスすることを確認する

| 4.8
| 40X系
| Compare.Operator.GREATER_THANが有効に働くこと（検証エラー）
a| * Integer型プロパティを持つクラスに `@Compare` を付与する
[source,java]
----
@Compare(left = "left",
    right = "right",
    operator = Compare.Operator.GREATER_THAN)
public class TestClass {
    private Integer left;
    private Integer right;
}
----
* `left` に `right` より小さな値を入力する
a| * 検証をパスせず、プロパティ `left` に対するエラーメッセージが表示されることを確認する

| 4.9
| 20X系
| Compare.Operator.GREATER_THAN_OR_EQUALが有効に働くこと（正常）
a| * Integer型プロパティを持つクラスに `@Compare` を付与する
[source,java]
----
@Compare(left = "left",
    right = "right",
    operator = Compare.Operator.GREATER_THAN_OR_EQUAL)
public class TestClass {
    private Integer left;
    private Integer right;
}
----
* `left` に `right` 以上の値を入力する
a| * 検証をパスすることを確認する

| 4.10
| 40X系
| Compare.Operator.GREATER_THAN_OR_EQUALが有効に働くこと（検証エラー）
a| * Integer型プロパティを持つクラスに `@Compare` を付与する
[source,java]
----
@Compare(left = "left",
    right = "right",
    operator = Compare.Operator.GREATER_THAN_OR_EQUAL)
public class TestClass {
    private Integer left;
    private Integer right;
}
----
* `left` に `right` より小さな値を入力する
a| * 検証をパスせず、プロパティ `left` に対するエラーメッセージが表示されることを確認する

| 4.11
| 20X系
| Compare.Operator.LESS_THANが有効に働くこと（正常）
a| * Integer型プロパティを持つクラスに `@Compare` を付与する
[source,java]
----
@Compare(left = "left",
    right = "right",
    operator = Compare.Operator.LESS_THAN)
public class TestClass {
    private Integer left;
    private Integer right;
}
----
* `left` に `right` より小さな値を入力する
a| * 検証をパスすることを確認する

| 4.12
| 40X系
| Compare.Operator.LESS_THANが有効に働くこと（検証エラー）
a| * Integer型プロパティを持つクラスに `@Compare` を付与する
[source,java]
----
@Compare(left = "left",
    right = "right",
    operator = Compare.Operator.LESS_THAN)
public class TestClass {
    private Integer left;
    private Integer right;
}
----
* `left` に `right` 以上の値を入力する
a| * 検証をパスせず、プロパティ `left` に対するエラーメッセージが表示されることを確認する

| 4.13
| 20X系
| Compare.Operator.LESS_THAN_OR_EQUALが有効に働くこと（正常）
a| * Integer型プロパティを持つクラスに `@Compare` を付与する
[source,java]
----
@Compare(left = "left",
    right = "right",
    operator = Compare.Operator.LESS_THAN_OR_EQUAL)
public class TestClass {
    private Integer left;
    private Integer right;
}
----
* `left` に `right` 以下の値を入力する
a| * 検証をパスすることを確認する

| 4.14
| 40X系
| Compare.Operator.LESS_THAN_OR_EQUALが有効に働くこと（検証エラー）
a| * Integer型プロパティを持つクラスに `@Compare` を付与する
[source,java]
----
@Compare(left = "left",
    right = "right",
    operator = Compare.Operator.LESS_THAN_OR_EQUAL)
public class TestClass {
    private Integer left;
    private Integer right;
}
----
* `left` に `right` より大きな値を入力する
a| * 検証をパスせず、プロパティ `left` に対するエラーメッセージが表示されることを確認する

| 4.15
| 40X系
| Compare.Node.PROPERTYが有効に働くこと（検証エラー）
a| * Integer型プロパティを持つクラスに `@Compare` を付与する
[source,java]
----
@Compare(left = "left",
    right = "right",
    operator = Compare.Operator.EQUAL,
    node = Compare.Node.PROPERTY)
public class TestClass {
    private Integer left;
    private Integer right;
}
----
* `left` と `right` に異なる値を入力する
a| * 検証をパスせず、プロパティ `left` に対するエラーメッセージが表示されることを確認する

| 4.16
| 40X系
| Compare.Node.ROOT_BEANが有効に働くこと（検証エラー）
a| * Integer型プロパティを持つクラスに `@Compare` を付与する
[source,java]
----
@Compare(left = "left",
    right = "right",
    operator = Compare.Operator.EQUAL,
    node = Compare.Node.ROOT_BEAN)
public class TestClass {
    private Integer left;
    private Integer right;
}
----
* `left` と `right` に異なる値を入力する
a| * 検証をパスせず、ルートBeanに対するエラーメッセージが表示されることを確認する

| 4.17
| 40X系
| 日本語ロケールを指定した場合に、日本語メッセージが表示されること（検証エラー）
a| * 4.2と同様
* LocaleResolverを利用して日本語ロケールに変更する
a| * 日本語エラーメッセージが表示されること

|

|===
